[workspace]
members = [
    "borsh-sherde",
    "concurrent",
    "hello-async",
    "minigrep",
    "rust", "week28",
]

[package]
name = "cohort-web3"
version = "0.1.0"
edition = "2024"

[dependencies]
